# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - proto-web-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_aa37310dca1949b6b83164e82a3c1754 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_569e0fe1db44402b9f6bf38b2ad03cfa }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_aa37310dca1949b6b83164e82a3c1754 }}/oksuriini/catregistry:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'proto-web-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_24247e1bb9f24646ae3f0ba0659e3760 }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_aa37310dca1949b6b83164e82a3c1754 }}/oksuriini/catregistry:${{ github.sha }}'